export const CONTENT_CHANGE_PENDING = "CONTENT_CHANGE_PENDING";
export const CONTENT_CHANGE_SUCESS = "CONTENT_CHANGE_SUCESS";
export const CONTENT_CHANGE_FAILED = "CONTENT_CHANGE_FAILED";
export const CONTENT_CHANGE_SET = "CONTENT_CHANGE_SET";

export const ROUTE_CHANGE = "ROUTE_CHAGE";